"use client";

import { useEffect, useState, type CSSProperties } from "react";
import { getUserProfile } from "@/app/actions/auth";
import {
  getReportDataForDate,
  upsertDailyObservation,
  type DailyObservation,
} from "@/app/actions/report";
import Header from "@/components/Header";
import { AppProvider } from "@/lib/store";
import {
  type ReportUserProfile,
  readStoredUserProfile,
  toReportProfile,
  toStoredUserProfileFromServerUser,
  writeStoredUserProfile,
} from "@/lib/userProfileStorage";

type UserProfile = ReportUserProfile;

interface ObservationFormValues {
  actualWakeMin: number;
  actualSleepMin: number;
  avgSleepDurationMin: number;
  peak1ActualStart: number;
  low1ActualStart: number;
  avgSessionDurationPct: number;
  recoveryAdherencePct: number;
  contextSwitchesPerDay: number;
  deadlineBufferDays: number;
}

function fmt(minutes: number): string {
  const h = Math.floor(((minutes % 1440) + 1440) % 1440 / 60)
    .toString()
    .padStart(2, "0");
  const m = (((minutes % 1440) + 1440) % 1440 % 60).toString().padStart(2, "0");
  return `${h}:${m}`;
}

function toTimeInput(minute: number): string {
  return fmt(minute);
}

function fromTimeInput(value: string, fallback: number): number {
  const [h, m] = value.split(":").map(Number);
  if (!Number.isFinite(h) || !Number.isFinite(m)) return fallback;
  const total = h * 60 + m;
  if (total < 0 || total > 1439) return fallback;
  return total;
}

function sleepSpan(wake: number, sleep: number): number {
  return wake > sleep ? wake - sleep : 1440 - sleep + wake;
}

function toObservationForm(
  profile: UserProfile,
  observation?: DailyObservation,
): ObservationFormValues {
  return {
    actualWakeMin: observation?.actualWakeMin ?? profile.wake_sleep.wake,
    actualSleepMin: observation?.actualSleepMin ?? profile.wake_sleep.sleep,
    avgSleepDurationMin:
      observation?.avgSleepDurationMin ??
      sleepSpan(profile.wake_sleep.wake, profile.wake_sleep.sleep),
    peak1ActualStart:
      observation?.peak1ActualStart ??
      (profile.peak_focus_windows[0]?.start_min ?? 540),
    low1ActualStart:
      observation?.low1ActualStart ??
      (profile.low_energy_windows[0]?.start_min ?? 840),
    avgSessionDurationPct: observation?.avgSessionDurationPct ?? 100,
    recoveryAdherencePct: observation?.recoveryAdherencePct ?? 100,
    contextSwitchesPerDay: observation?.contextSwitchesPerDay ?? 0,
    deadlineBufferDays: observation?.deadlineBufferDays ?? 0,
  };
}

function FeedbackContent() {
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [observation, setObservation] = useState<DailyObservation | null>(null);
  const [form, setForm] = useState<ObservationFormValues | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [source, setSource] = useState("pending");

  useEffect(() => {
    let isMounted = true;

    async function loadData() {
      let resolvedProfile: UserProfile | null = null;

      const localProfile = readStoredUserProfile();
      if (localProfile) {
        resolvedProfile = toReportProfile(localProfile);
        if (isMounted) setProfile(resolvedProfile);
      }

      if (!resolvedProfile) {
        try {
          const { user, error } = await getUserProfile();
          if (!error && user) {
            const normalized = toStoredUserProfileFromServerUser(user);
            if (normalized) {
              resolvedProfile = toReportProfile(normalized);
              if (isMounted) {
                writeStoredUserProfile(normalized);
                setProfile(resolvedProfile);
              }
            }
          }
        } catch {
          // no-op
        }
      }

      try {
        const result = await getReportDataForDate();
        if (!isMounted) return;

        if (result.error) {
          setMessage(result.error);
        }

        if (result.observation) {
          setObservation(result.observation);
          setSource(result.autoGenerated ? "auto-generated" : "saved");
          setMessage(
            result.autoGenerated
              ? "Values were auto-generated from today's scheduler activity. You can refine them and save."
              : "Loaded your saved values for today.",
          );

          if (resolvedProfile) {
            setForm(toObservationForm(resolvedProfile, result.observation));
          }
        } else if (resolvedProfile) {
          setForm(toObservationForm(resolvedProfile));
          setSource("manual");
        }
      } catch {
        if (isMounted) {
          setMessage("Unable to load report feedback data.");
          if (resolvedProfile) {
            setForm(toObservationForm(resolvedProfile));
          }
        }
      } finally {
        if (isMounted) setLoaded(true);
      }
    }

    loadData();

    return () => {
      isMounted = false;
    };
  }, []);

  async function saveFeedback() {
    if (!form) return;

    setSaving(true);
    setMessage(null);

    const result = await upsertDailyObservation({
      metricDate: new Date().toISOString().slice(0, 10),
      actualWakeMin: form.actualWakeMin,
      actualSleepMin: form.actualSleepMin,
      avgSleepDurationMin: form.avgSleepDurationMin,
      peak1ActualStart: form.peak1ActualStart,
      low1ActualStart: form.low1ActualStart,
      avgSessionDurationPct: form.avgSessionDurationPct,
      recoveryAdherencePct: form.recoveryAdherencePct,
      contextSwitchesPerDay: form.contextSwitchesPerDay,
      deadlineBufferDays: form.deadlineBufferDays,
    });

    if (result.error) {
      setMessage(`Failed: ${result.error}`);
      setSaving(false);
      return;
    }

    if (result.observation) {
      setObservation(result.observation);
      setSource("saved");
      setMessage("Feedback saved. Report comparisons can now use these observed values.");
      if (profile) {
        setForm(toObservationForm(profile, result.observation));
      }
    }

    setSaving(false);
  }

  const labelStyle: CSSProperties = {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "var(--muted)",
    marginBottom: 6,
  };

  const inputStyle: CSSProperties = {
    width: "100%",
    padding: "8px 10px",
    border: "0.5px solid var(--rule)",
    background: "var(--bg)",
    color: "var(--ink)",
    fontFamily: "var(--mono)",
    fontSize: 13,
  };

  return (
    <div style={{ minHeight: "100vh" }}>
      <Header />

      <section className="container section-rule" style={{ paddingTop: 80, paddingBottom: 36 }}>
        <div className="meta-text" style={{ marginBottom: 10 }}>Feedback / Updates</div>
        <h1 style={{ marginBottom: 12 }}>Daily observed values</h1>
        <p style={{ color: "var(--muted)", fontSize: 13, lineHeight: 1.8, maxWidth: 900 }}>
          Update your real daily values here. Baseline remains your onboarding reference. The report tab can compare baseline vs observed drift using this data.
        </p>
      </section>

      <main className="container" style={{ paddingTop: 36, paddingBottom: 80, maxWidth: 1100 }}>
        {!loaded && (
          <div style={{ textAlign: "center", padding: "80px 0", color: "var(--muted)" }}>
            Loading feedback data...
          </div>
        )}

        {loaded && !profile && (
          <div style={{ padding: "40px 32px", border: "0.5px solid var(--rule)", background: "var(--card-bg)" }}>
            <div style={{ fontWeight: 700, marginBottom: 8 }}>No profile data</div>
            <p style={{ color: "var(--muted)", fontSize: 12, margin: 0 }}>
              Finish onboarding first to set your baseline.
            </p>
          </div>
        )}

        {loaded && profile && form && (
          <section style={{ border: "0.5px solid var(--rule)", background: "var(--card-bg)", padding: "20px 24px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", gap: 12, marginBottom: 16 }}>
              <div>
                <div className="meta-text" style={{ marginBottom: 6 }}>Today</div>
                <div style={{ fontSize: 12, color: "var(--muted)" }}>
                  Source: {source}
                </div>
              </div>
              <div className="meta-text" style={{ whiteSpace: "nowrap" }}>
                Baseline wake/sleep: {fmt(profile.wake_sleep.wake)} / {fmt(profile.wake_sleep.sleep)}
              </div>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 12 }}>
              <div>
                <div style={labelStyle}>Actual wake</div>
                <input
                  type="time"
                  value={toTimeInput(form.actualWakeMin)}
                  onChange={(e) => setForm({ ...form, actualWakeMin: fromTimeInput(e.target.value, form.actualWakeMin) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Actual sleep</div>
                <input
                  type="time"
                  value={toTimeInput(form.actualSleepMin)}
                  onChange={(e) => setForm({ ...form, actualSleepMin: fromTimeInput(e.target.value, form.actualSleepMin) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Sleep duration (min)</div>
                <input
                  type="number"
                  min={0}
                  max={1440}
                  value={form.avgSleepDurationMin}
                  onChange={(e) => setForm({ ...form, avgSleepDurationMin: Number(e.target.value || 0) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Peak focus start</div>
                <input
                  type="time"
                  value={toTimeInput(form.peak1ActualStart)}
                  onChange={(e) => setForm({ ...form, peak1ActualStart: fromTimeInput(e.target.value, form.peak1ActualStart) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Low energy start</div>
                <input
                  type="time"
                  value={toTimeInput(form.low1ActualStart)}
                  onChange={(e) => setForm({ ...form, low1ActualStart: fromTimeInput(e.target.value, form.low1ActualStart) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Session completion %</div>
                <input
                  type="number"
                  min={0}
                  max={100}
                  step={0.1}
                  value={form.avgSessionDurationPct}
                  onChange={(e) => setForm({ ...form, avgSessionDurationPct: Number(e.target.value || 0) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Recovery adherence %</div>
                <input
                  type="number"
                  min={0}
                  max={100}
                  step={0.1}
                  value={form.recoveryAdherencePct}
                  onChange={(e) => setForm({ ...form, recoveryAdherencePct: Number(e.target.value || 0) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Context switches/day</div>
                <input
                  type="number"
                  min={0}
                  step={1}
                  value={form.contextSwitchesPerDay}
                  onChange={(e) => setForm({ ...form, contextSwitchesPerDay: Number(e.target.value || 0) })}
                  style={inputStyle}
                />
              </div>

              <div>
                <div style={labelStyle}>Deadline buffer (days)</div>
                <input
                  type="number"
                  step={1}
                  value={form.deadlineBufferDays}
                  onChange={(e) => setForm({ ...form, deadlineBufferDays: Number(e.target.value || 0) })}
                  style={inputStyle}
                />
              </div>
            </div>

            <div style={{ marginTop: 16, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}>
              <span className="meta-text" style={{ color: message?.startsWith("Failed") ? "var(--vermillion)" : "var(--muted)" }}>
                {message ?? "Save your observed data to compare against baseline."}
              </span>
              <button
                className="btn btn-primary"
                onClick={() => void saveFeedback()}
                disabled={saving}
                style={{ opacity: saving ? 0.65 : 1 }}
              >
                {saving ? "Saving..." : "Save feedback"}
              </button>
            </div>

            {observation && (
              <div style={{ marginTop: 14, paddingTop: 14, borderTop: "0.5px solid var(--rule)", color: "var(--muted)", fontSize: 12 }}>
                Last updated: {new Date(observation.updatedAt).toLocaleString("en-GB")}
              </div>
            )}
          </section>
        )}
      </main>
    </div>
  );
}

export default function FeedbackUpdatesView() {
  return (
    <AppProvider>
      <FeedbackContent />
    </AppProvider>
  );
}
